org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties (复用附属包已验证的 1.20.1 版本)
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
fabric_version=0.92.3+1.20.1

# Mod Properties
mod_version=0.0.1-beta
maven_group=com.mangzai.shapeshiftercompass
archives_base_name=shape-shifter-s-compass

# Optional (soft) dependency versions
trinkets_version=3.7.2
